### ISSUE TITLE
Installation Troubles

### ISSUE THREAD

**Issue by iamzeginger** [Lolispo/inhouseBot#19]
I downloaded the file, and run npm init through nodejs cmd but I am unable to find the config file? I'm not a coder so this is really hard. Please help :) Can PM me on discord at iAmZeGinger#6692. Thanks <3

**Comment by Samev** [comment]
I think the [installation guide](https://github.com/Lolispo/inhouseBot/wiki/Installation) is a bit out of date.
The configuration which is needed is made in ".env.SAMPLE" (but then rename it to simply ".env"), however you'll need to setup a database etc. for some functionality to work (I haven't tried launching the bot without the database so not sure to what extent it would work).

Also after running `npm init` you might need to run `npm install`.

**Comment by Lolispo** [comment]
@iamzeginger sadly this is not currently a plug and play inhouse bot application, but instead will require to setup your own bot in your discord server (follow discord step by step and provide it with access) and then configure a mysql database to store the inhouse information.
I updated the installation guide a bit with some requirements but as @Samev said, configuration is very outdated.
